export const OK = 'OK';
export const BAD_REQUEST = 'BAD_REQUEST';
export const INVALID_REQUEST = 'INVALID_REQUEST';
export const INVALID_OPERATION = 'INVALID_OPERATION';
export const NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';
export const AUTH_REQUIRED = 'AUTH_REQUIRED';
export const ANON_REQUIRED = 'ANON_REQUIRED';
